require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'tmp/**/*'
    - 'log/**/*'