default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *default
  database: blackbook_dev

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

