default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1

development:
  <<: *default
  database: blackbook_dev
  user: root

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: blackbook_test
  user: root

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
