default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1

development:
  <<: *default
  database: blackbook_dev

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # FIXME do we need to alternate using ENV['CI']?
  database: blackbook_test
